site_name: predictr - Predict the Reliability
theme:
  name: material

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    scheme: slate
  features:
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
nav:
    - Home: index.md
    - Getting started: get_started.md
    - Documentation: classes.md
    - Changelog: CHANGELOG.md
    - Medium Articles: medium.md
    - Cite predictr: citation.md
    - Contact me: contact.md
extra:
  analytics:
    provider: google
    property: G-CVKQLNG7QD
  social:
    - icon: fontawesome/brands/medium
      link: https://medium.com/@tamertevetoglu

# Repository
repo_name: tvtoglu/predictr
repo_url: https://github.com/tvtoglu/predictr
edit_uri: ""

markdown_extensions:
  - attr_list
  - toc:
      toc_depth: 6
